FROM alpine:latest #image reduite
COPY producer.sh /srv #ajout du script
WORKDIR /srv
RUN apk add --no-cache bash redis #installation de redis
CMD [ "bash","-c","./producer.sh" ] #éxecution du script
