FROM alpine:latest #image reduite
COPY consumer.sh /srv #ajout du script
WORKDIR /srv
RUN apk add --no-cache bash redis #installation de redis
CMD [ "bash","-c","./consumer.sh" ] #éxecution du script
